# Generated by Django 2.2.1 on 2019-05-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLinkList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InviteRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=256, unique=True)),
                ('firstname', models.TextField(max_length=50)),
                ('secondname', models.TextField(blank=True, max_length=50)),
                ('contacts', models.TextField(max_length=500)),
                ('about', models.TextField(max_length=2000)),
            ],
        ),
    ]
