# Generated by Django 2.2.1 on 2019-05-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_tags',
            field=models.TextField(blank=True, db_index=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='post',
            name='short_body',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(db_index=True, max_length=6000),
        ),
    ]
