# Generated by Django 2.2.1 on 2019-05-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190505_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttag',
            name='title',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
